### ISSUE TITLE
Convert xdrt files to dicom

### ISSUE THREAD

**Issue by ydehond6** [NKI-AI/xdrt#7]
It should be nice when it is possible to convert xvi .scan images to dicom images

**Comment by jonasteuwen** [comment]
I got a preliminary version working. It also requires parsing of the full XVI (to set the proper metadata). Likely I'll come up with something in the next few days.

**Comment by jonasteuwen** [comment]
@ydehond6 I have a preliminary version in https://github.com/NKI-AI/xdrt/tree/xvi_reader. 

You can install it from https://docs.aiforoncology.nl/xdrt/installation.html#install-from-sources, but is `git checkout xvi_reader`. Conversion is then done using `xvi2dcm <input folder> <output folder>`. I hope you have the time to test it on some of your cases. Likely there is some relevant metadata still missing, but at least for me they seem to open correctly.

**Comment by ydehond6** [comment]
Thank you! It works for my data
